<?php
#/root>includes/functions-template.php
/**
 * Created by PhpStorm.
 * User: Hoang
 * Date: 11/11/2015
 * Time: 10:18
 */
include_once (dirname(__FILE__). '/theme.php');

/**
 * Class HW__Site
 */
class HW__Site {
    /**
     * @var null
     */
    protected $msg = null;
    /**
     * main class constructor
     */
    public function __construct() {
        //admin notice
        if(is_admin()) {
            $this->msg = HW_WP_NOTICES::get_instance(null);
            $this->admin_hooks() ;
        }

    }

    /**
     * prepare admin hooks
     */
    private function admin_hooks() {
        add_action('before_switch_theme', array($this, '_before_switch_theme'));
        hw_register_theme_deactivation_hook('',array($this, '_theme_deactivation_hook'));
    }

    /**
     * init hooks for site on frontend
     */
    private function site_hooks() {
        add_filter( 'wp_title', array($this,'_wp_title'), 10, 2 );
    }
    /**
     * on theme deactivation hook
     */
    public function _theme_deactivation_hook() {
        //unregister all sidebars
        hwawc_unregister_all_sidebars();
    }
    /**
     * @hook before_switch_theme
     */
    public function _before_switch_theme() {
        //check theme for validate
        if(!HW__Template::validate_theme()) {
            $this->msg->put_msg('Lỗi theme không hợp lệ !');
            return false;
        }
        return true;
    }
    /**
     * update logo
     * @param $url
     * @param $set_related
     */
    public static function set_logo($url, $set_related= true) {
        if(HW_URL::valid_url($url)) {
            set_theme_mod('image_logo', esc_url_raw( set_url_scheme($url)));
            if($set_related) HW_NHP_Main_Settings::update_data(array('admin_logo' => $url));
            return true;
        }
    }

    /**
     * update banner
     * @param $url
     * @param $set_related
     */
    public static function set_banner($url, $set_related = true) {
        if(HW_URL::valid_url($url)) {
            set_theme_mod( 'header_image', esc_url_raw( set_url_scheme($url)) );
            if($set_related) HW_NHP_Main_Settings::update_data(array('site_banner' => $url));
            return true;
        }
        //trailingslashit( get_stylesheet_directory_uri() ).'images/banner.jpg'
        //define('HEADER_IMAGE', $url);
    }

    /**
     * update site information
     * @param $info
     * @param $set_related
     */
    public static function update_site_info($info, $set_related= true) {
        if(is_string($info)) $info = array('name' => $info);
        //blog name
        if(isset($info['name'])) {
            $info['site_name'] = $info['name'];
            update_option('blogname', $info['name']);
        }
        //blogdescription
        if(isset($info['description'])) {
            $info['slogan'] = $info['description'];
            update_option('blogdescription', $info['description']);
        }
        //update admin email
        if(!empty($info['email'])) $info['email'] = 'hotro@hoangweb.com';
        update_option('admin_email', $info['email']);

        //flush permalink
        update_option('permalink_structure', '/%category%/%postname%.html');
        flush_rewrite_rules();

        if(!isset($info['wp_head_script'])) $info['wp_head_script'] = '<script>/*generated by hoangweb engine*/</script>';
        //set relate options & other
        HW_NHP_Main_Settings::update_data($info);
    }
    /**
     * Creates a nicely formatted and more specific title element text
     * for output in head of document, based on current view.
     *
     * @since hoangweb 1.0
     *
     * @param string $title Default title text for current view.
     * @param string $sep Optional separator.
     * @return string Filtered title.
     */
    public function _wp_title( $title, $sep ) {
        global $paged, $page;

        if ( is_feed() )
            return $title;

        // Add the site name.
        $title .= get_bloginfo( 'name' );

        // Add the site description for the home/front page.
        $site_description = get_bloginfo( 'description', 'display' );
        if ( $site_description && ( is_home() || is_front_page() ) )
            $title = "$title $sep $site_description";

        // Add a page number if necessary.
        if ( $paged >= 2 || $page >= 2 )
            $title = "$title $sep " . sprintf( __( 'Page %s', 'hoangweb' ), max( $paged, $page ) );

        return $title;
    }
}
/**
 * Class HW_Site_Template_Parser
 */
if(class_exists('TimberSite', false)):
class HW_Site_Template_Parser extends TimberSite {
    /**
     * main class constructor
     */
    function __construct() {
        add_theme_support( 'post-formats' );
        add_theme_support( 'post-thumbnails' );
        add_theme_support( 'menus' );

        add_filter( 'timber_context', array( $this, 'add_to_context' ) );
        add_filter( 'get_twig', array( $this, 'add_to_twig' ) );
        add_action( 'init', array( $this, 'register_post_types' ) );
        add_action( 'init', array( $this, 'register_taxonomies' ) );

        parent::__construct();
    }
    function register_post_types() {
        //this is where you can register custom post types
    }

    function register_taxonomies() {
        //this is where you can register custom taxonomies
    }
    /**
     * @param $context
     * @return mixed
     */
    public function add_to_context( $context ) {
        //$context['context'] = Timber::get_context();  //make infinitive loop
        $context['menu'] = HW_Site_Menu::get_instance();  //menus manager
        $context['site'] = $this;
        //$context['sidebar'] = Timber::get_sidebar('sidebar.php');
        //$context['sidebar_left'] = Timber::get_sidebar(['sidebar-left.php','sidebar.php']);
        $context['position'] = new HW_Site_Position();
        $context['sidebar'] = new HW_Site_Sidebar();
        //$context['menu']->main_menu();exit;
        return $context;
    }

    /**
     * site logo
     * @return string
     */
    public function logo() {
        return get_theme_mod('image_logo');
    }

    /**
     * get site banner
     * @return false|string
     */
    public function header_image() {
        return get_header_image();
    }

    /**
     * @param $twig
     * @return mixed
     */
    public function add_to_twig( $twig ) {
        /* this is where you can add your own fuctions to twig */
        $twig->addExtension( new Twig_Extension_StringLoader() );
        #$twig->addFilter( 'myfoo', new Twig_Filter_Function( 'myfoo' ) );
        return $twig;
    }

}
endif;
//new HW_Site();  //site
add_action('hw_hoangweb_loaded', '_hw_site_init');
function _hw_site_init() {
    new HW__Site();
}

